In [21]:
import numpy as np

# Slicing 


In [22]:
# Basic = [start : end : step]

# 'end' index is not included to array

arr = np.array ([1,2,3,4,5,6,7])

print (arr[1:5:2])

# It is possible to skip 

print (arr[4:])

print (arr[:4])

print (arr[::2])

# Negative Indices

print (arr[-3:-1])

[2 4]
[5 6 7]
[1 2 3 4]
[1 3 5 7]
[5 6]


In [23]:
# Slicing 2-D Arrays

# Indexing two-dimensional data is similar to indexing one-dimensional data, except that a comma is used to separate the index for each dimension

# [Row, Column]

arr = np.array ([[1,2,3,4,5], [6,7,8,9,10]])

print (arr[1, 1:4])

print (arr[0:1, 2])

print (arr[0:2, 1:4])

[7 8 9]
[3]
[[2 3 4]
 [7 8 9]]


In [24]:
# Example 1

a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

b = a [:2, 1:3]

print (b)

print (a[0,1])

# A slice of an array is a view into the same data, so modifying it will modify the original array. 

b[0,0] = 77

print (a[0,1])

[[2 3]
 [6 7]]
2
77


In [27]:
# Example 2

a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

# Mixing integer indexing with slices yields an array of lower rank.

row_r1 = a[1:2, :]
print (row_r1, row_r1.shape)

# While using only slices yields an array of the same rank as the original array 

row_r2 = a[1, :]
print (row_r2, row_r2.shape)

# Column

col_r1 = a[:, 1]
print (col_r1, col_r1.shape)

col_r2 = a[:, 1:2]
print (col_r2, col_r2.shape)

[[5 6 7 8]] (1, 4)
[5 6 7 8] (4,)
[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)


In [33]:
# Example 3. Integer Array Indexing 

a = np.array ([[1,2],[3,4],[5,6]])

print (a[[0,1,2],[0,1,0]])

[1 4 5]


# Reshaping

In [17]:
# Reshape 1D to 2D Array

data = [11,22,33,44,55]
data = np.array(data)
data = data.reshape((data.shape[0],1))
print (data)

[[11]
 [22]
 [33]
 [44]
 [55]]


In [18]:
# Reshape 2D to 3D Array

data = [[11,22],[33,44],[55,66]]
data = np.array(data)
print (data.shape)

data = data.reshape((data.shape[0],data.shape[1],1))
print (data)

(3, 2)
[[[11]
  [22]]

 [[33]
  [44]]

 [[55]
  [66]]]


# Newaxis 

In [44]:
# Example 1. 

a = np.arange (4)
b = a[np.newaxis, :]
c = a[:, np.newaxis]
print (a, a.shape)
print (b, b.shape)
print (c, c.shape)

[0 1 2 3] (4,)
[[0 1 2 3]] (1, 4)
[[0]
 [1]
 [2]
 [3]] (4, 1)


In [36]:
# Example 2. 

b = np.arange(12).reshape(3,4)

b_new1 = b [:,:,np.newaxis]
b_new2 = b [:,np.newaxis,:]

print (b)
print (b_new1)
print (b_new2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[[ 0]
  [ 1]
  [ 2]
  [ 3]]

 [[ 4]
  [ 5]
  [ 6]
  [ 7]]

 [[ 8]
  [ 9]
  [10]
  [11]]]
[[[ 0  1  2  3]]

 [[ 4  5  6  7]]

 [[ 8  9 10 11]]]


In [48]:
# Example 3. 

x1 = np.arange(5)
x2 = np.arange(3)

x1_new = x1[:, np.newaxis]
print (x1_new, x1_new.shape)

print (x1_new + x2)

[[0]
 [1]
 [2]
 [3]
 [4]] (5, 1)
[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]]


In [50]:
a = np.arange(5*5).reshape(5,5)

print (a, a.shape)

a_3D = a[np.newaxis, ...]
print (a_3D, a_3D.shape)

a_4D = a[np.newaxis, ..., np.newaxis]
print (a_4D, a_4D.shape)


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]] (5, 5)
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]
  [20 21 22 23 24]]] (1, 5, 5)
[[[[ 0]
   [ 1]
   [ 2]
   [ 3]
   [ 4]]

  [[ 5]
   [ 6]
   [ 7]
   [ 8]
   [ 9]]

  [[10]
   [11]
   [12]
   [13]
   [14]]

  [[15]
   [16]
   [17]
   [18]
   [19]]

  [[20]
   [21]
   [22]
   [23]
   [24]]]] (1, 5, 5, 1)


# Tile 

In [40]:
a = np.arange(4)

print (a)
print (a.shape)

b = np.tile (a,2)
print (b)

c = np.tile (a,(2,2))
print (c)

[0 1 2 3]
(4,)
[0 1 2 3 0 1 2 3]
[[0 1 2 3 0 1 2 3]
 [0 1 2 3 0 1 2 3]]


# Integer Array Indexing 